name: Infodump updates

on:
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

    # Run on daily schedule, UTC
    schedule:
        - cron: "30 12 * * *"

permissions:
    contents: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
    group: "infodump"
    cancel-in-progress: false

jobs:
    infodump:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  token: ${{ secrets.INFODUMP_ACCESS_TOKEN }}

            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.11"
                  cache: "pip"

            - name: Install pip requirements
              run: pip install -r parser/requirements.txt

            - name: Check for Infodump updates
              run: python parser/download.py infodump src/data/data.json

            - name: Push any update
              run: |
                  git config --global user.name 'mefi-activity-automated'
                  git config --global user.email 'mefi-activity-automated'
                  git add src/data/data.json
                  if ! git diff-index --quiet HEAD; then
                    git commit -m "Infodump updated: $(jq -r "._published" src/data/data.json)"
                    git push
                  fi
