name: Check for Infodump updates

on:
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

    # Run on daily schedule, UTC
    schedule:
        - cron: "23 6 * * *"

permissions:
    contents: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
    group: "infodump"
    cancel-in-progress: false

jobs:
    infodump:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  token: ${{ secrets.INFODUMP_ACCESS_TOKEN }}
            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.11"
            - name: Check for Infodump updates
              run: python download.py --live public/data.js
            - name: Push any changes
              run: |
                  git config --global user.name 'Infodump automated update'
                  git config --global user.email 'klipspringr@users.noreply.github.com'
                  git add public/data.js
                  if ! git diff-index --quiet HEAD; then
                    git commit -m "Infodump automated update"
                    git push
                  fi
