name: Check for Infodump updates

on:
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

    # Run on daily schedule, UTC
    schedule:
        - cron: "50 12 * * *"

permissions:
    contents: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
    group: "infodump-check"
    cancel-in-progress: false

jobs:
    infodump-check:
        runs-on: ubuntu-latest
        env:
            DATA_JSON: src/data/data.json
        steps:
            - name: Checkout
              uses: actions/checkout@v6
              with:
                  token: ${{ secrets.INFODUMP_ACCESS_TOKEN }}

            - name: Setup Python
              uses: actions/setup-python@v6
              with:
                  python-version: "3.13"
                  cache: "pip"

            - name: Install pip requirements
              run: pip install -r infodump_tools/requirements.txt

            - name: Check for Infodump updates
              env:
                  INFODUMP_USER_AGENT: ${{ secrets.INFODUMP_USER_AGENT }}
                  PYTHONUNBUFFERED: 1
              run: python -m infodump_tools.download infodump "$DATA_JSON"

            - name: Push update (if any)
              run: |
                if ! git diff-index --quiet HEAD -- "$DATA_JSON"; then
                  git config user.name 'mefi-activity-automated'
                  git config user.email 'mefi-activity-automated'
                  git add "$DATA_JSON"
                  git commit -m "Infodump updated: $(jq -r "._published" "$DATA_JSON")"
                  git push
                fi

            - name: Archive Infodump (if any)
              env:
                  RESTIC_REPOSITORY: ${{ secrets.RESTIC_REPOSITORY }}
                  RESTIC_PASSWORD: infodump
                  RESTIC_COMPRESSION: max
                  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              run: |
                if [ -d infodump ]; then
                  sudo apt-get update
                  sudo apt-get install -y restic
                  restic snapshots || restic init
                  restic backup infodump --verbose
                  restic check
                  restic stats --mode raw-data
                fi
